# SPDX-FileCopyrightText: 2023 René de Hesselle <dehesselle@web.de>
#
# SPDX-License-Identifier: GPL-2.0-or-later

variables:
  GIT_DEPTH: 1
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

include:
  - remote: https://raw.githubusercontent.com/dehesselle/sdkchecksum/master/.gitlab-ci/verify_sdk-template.yml

#------------------------------------------------------------------------- build

build:
  stage: build
  parallel:
    matrix:
      - ARCHITECTURE: [ "arm64", "x86_64" ]
  rules:
    - if: $ARCHITECTURE == "x86_64"
      variables:
        SDKROOT: /opt/sdks/MacOSX10.13.4.sdk
    - if: $ARCHITECTURE == "arm64"
      variables:
        SDKROOT: /opt/sdks/MacOSX11.3.sdk
  tags:
    - macos
    - ${ARCHITECTURE}
  variables:
    MELD_BUILD: $CI_PIPELINE_IID
  script:
    - !reference [ .verify_sdk, script ]
    - ./build_toolset.sh
    - ./build_meld.sh
  after_script:
    # For persistent runners: cleanup afterwards.
    - |
      VER_DIR=$(jhb/usr/bin/config get VER_DIR)
      rm -rf ${VER_DIR:?}
  artifacts:
    paths:
      - Meld*.dmg
